### ISSUE TITLE
Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by Sven-ybj** [aMarCruz/react-native-shortcut-badge#1]
"react-native": "0.46.2"

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ttttt/App/node_modules/react-native-shortcut-badge/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-shortcut-badge'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by aMarCruz** [comment]
@Sven-ybj sorry. This library requires Gradle 4.x. This is declared in android/gradle/wrapper/gradle-wrapper.properties

I will update the docs with this.

**Comment by Sven-ybj** [comment]
@aMarCruz Ok, thank you
