### ISSUE TITLE
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

### ISSUE THREAD

**Issue by aoarashi1988** [aMarCruz/react-native-shortcut-badge#2]
## Where:
Build file 'F:\RN_DEMO\notification_badge demo\node_modules\react-native-shortcut-badge\android\build.gradle' line: 59

## What went wrong:
A problem occurred evaluating project ':react-native-shortcut-badge'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

## Environment：
react-native: 0.55.4
OS: Windows 7

Anyway, thanks a lot for your contribution with the  ShortcutBadge

**Comment by aMarCruz** [comment]
@aoarashi1988 sorry, this library requires Gradle 4.x. This is declared in android/gradle/wrapper/gradle-wrapper.properties.

I will update the docs with this.

BTW: React Native 0.57 will use Gradle 4.4 as well. So `compileOnly` and `implementation` will be recognize in the default build.
