### ISSUE TITLE
Badge not shown in Android Galaxy S9

### ISSUE THREAD

**Issue by udarts** [aMarCruz/react-native-shortcut-badge#3]
I am using this extension for my react-native app.
On iOS it shows the badge on the icon, but on Android it is not showing (enabled for app in settings phone).

Any idea why?

**Comment by aMarCruz** [comment]
There's no universal support for Android badges, it depends on the version, model, and manufacturer of the device and user preferences (installed launcher). Right now, seems that Android Oreo and later is not working (it has native support for user controlled badges).

You can install the [ShortcutBadger tester app](https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking) from the PlayStore to find if a given is supported.

More info in https://github.com/leolin310148/ShortcutBadger.

Closing this issue now.
